swagger: '2.0'
info:
  title: 'My API'
  version: '1.0'
paths:
  /hello:
    get:
      responses:
        '200':
          description: 'OK'
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations