Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Default: kp_06_july_2025

Resources:
  cfVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  cfSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref cfVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: ap-south-1a

  cfSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref cfVPC
      CidrBlock: 10.0.9.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: ap-south-1b

  ec2WithVnc:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03f4878755434977f
      InstanceType: t3.large
      KeyName: !Ref KeyPairName
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          VolumeSize: 30
          VolumeType: gp3
          DeleteOnTermination: true
      UserData:
        Fn::Base64: |
          #!/bin/bash
          apt update -y
          apt-get install -y apache2
          service apache2 start
          cat <<EOF > /var/www/html/index.html
          <!DOCTYPE html>
          <html>
          <head>
          <title>Please wait while startup script completes</title>
          </head>
          <body>
          <h1>Please wait while startup script completes..</h1>
          <h2>Video Tutorial</h2>
          <iframe width="728" height="447" src="https://www.youtube.com/embed/56iJ0n6Us9k" title="EC2 instance with desktop environment | launch using cloudformation template | aws | automation" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
          <script>
              function getRandomInt() {
                  return Math.floor(Math.random() * 256);
              }
              var color = 'rgb(' + getRandomInt() + ',' + getRandomInt() + ',' + getRandomInt() + ')';
              document.querySelector("h1").style.color = color;
              setInterval(function() {
                  location.reload();
              }, 1000);
          </script>
          </body>
          </html>
          EOF
          apt install xfce4 xfce4-goodies -y
          apt install tightvncserver -y
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f -y
          
          # Install Java (OpenJDK 17)
          apt install -y openjdk-17-jdk
          
          # Install Eclipse
          # Install Eclipse
          cd /opt
          wget "https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2024-12/R/eclipse-java-2024-12-R-linux-gtk-x86_64.tar.gz&r=1" -O eclipse.tar.gz
          tar -xzf eclipse.tar.gz
          rm eclipse.tar.gz
          ln -s /opt/eclipse/eclipse /usr/local/bin/eclipse
          
          # Create desktop shortcut for Eclipse
          mkdir -p /home/ubuntu/Desktop
          cat <<ECLIPSEEOF > /home/ubuntu/Desktop/eclipse.desktop
          [Desktop Entry]
          Type=Application
          Name=Eclipse
          Comment=Eclipse IDE
          Exec=/opt/eclipse/eclipse
          Icon=/opt/eclipse/icon.xpm
          Terminal=false
          Categories=Development;IDE;
          ECLIPSEEOF
          chmod +x /home/ubuntu/Desktop/eclipse.desktop
          chown ubuntu:ubuntu /home/ubuntu/Desktop/eclipse.desktop
          
          public_ip=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
          echo RUN vncserver AND SETUP THE PASSWORD
          echo THEN RUN ssh -L 5901:localhost:5901 -i ${KeyPairName}.pem ubuntu@$public_ip WITH YOUR LOCAL MACHINE AND THEN CONNECT USING A VNC VIEWER CLIENT AT "$public_ip":5901
          echo echo ssh -L 5901:localhost:5901 -i ${KeyPairName}.pem ubuntu@$public_ip>/home/ubuntu/tunnelvnc.sh
          echo Run the above ssh command in your local machine after runnign vncserver command to setup the password >>/home/ubuntu/tunnelvnc.sh
          chmod a+x /home/ubuntu/tunnelvnc.sh
          cat <<EOF > /var/www/html/index.html
          <!DOCTYPE html>
          <html>
          <head>
          <title>Vnc viewer setup done</title>
          </head>
          <body>
          <h1>Vnc viewer setup done</h1>
          <p>Run 'vncserver' in the ec2($public_ip) ternimal to setup vnc password</p>
          <p>Then run this in terminal/command line from your local machine where you have vncviewer installed: ssh -L 5901:localhost:5901 -i ${KeyPairName}.pem ubuntu@$public_ip  </p>
          <p>Finally connect to "localhost:5901" using your vncviewer client</p>
          <h2>Installed Software</h2>
          <ul>
          <li>Google Chrome</li>
          <li>Java (OpenJDK 17)</li>
          <li>Eclipse IDE (2024-12)</li>
          </ul>
          <h2>Video Tutorial</h2>
          <iframe width="728" height="447" src="https://www.youtube.com/embed/56iJ0n6Us9k" title="EC2 instance with desktop environment | launch using cloudformation template | aws | automation" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
          </body>
          </html>
          EOF
          systemctl enable apache2
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          DeleteOnTermination: true
          SubnetId: !Ref cfSubnet1
          GroupSet:
            - !Ref MySecurityGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref cfVPC
      GroupDescription: Allow SSH and HTTP traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5901
          ToPort: 5901
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: {}

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref cfVPC
      InternetGatewayId: !Ref MyInternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref cfVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref cfSubnet1
      RouteTableId: !Ref PublicRouteTable

  MyNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref cfVPC

  MyNetworkAclEntryIngress1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref MyNetworkAcl
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      Egress: false
      PortRange:
        From: 22
        To: 22

  MyNetworkAclEntryEgress1:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref MyNetworkAcl
      RuleNumber: 100
      Protocol: 6
      RuleAction: allow
      CidrBlock: 0.0.0.0/0
      Egress: true
      PortRange:
        From: 22
        To: 22